name: PR
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        env:
          BINDIR: /github/home/bin
        run: ./hack/linter.sh
        continue-on-error: false